#### Write a program to take name and age from user and print a greeting message

In [7]:
name = input("Please enter your name")
age = int(input("Please enter your age"))

if(age>=18):
    print(f"Hi, {name} your age is {age}. So you can cast your vote for this upcoming election")
else:
     print(f"Hi, {name} your age is {age}. Voters must be 18 years or older")

Please enter your name Poo
Please enter your age 9

Hi, Poo your age is 9. Voters must be 18 years or older

#### Create a list of numbers and print only even number

In [11]:
list1 = [1,2,3,5,90,80,67,78,45,29,9,990,70,28,12,34,35]
output1 = []

print(f'Number of elements present in list : {len(list1)}')
for i in range(1, len(list1)):
    if(list1[i] % 2 == 0):
        output1.append(list1[i])

print(f'Number of even elements present in list : {len(output1)}')
print(f'Even number array : {output1}')

Number of elements present in list : 17
Number of even elements present in list : 9
Even number array : [2, 90, 80, 78, 990, 70, 28, 12, 34]

#### Exception Handling - Divison by zero

In [19]:
input1 = int(input("Enter dividend number :"))
input2 = int(input("Enter divisor number :"))

try: 
    output = input1/input2
    print(f'Divison output : {output}')
except ZeroDivisionError:
    print("Error: numbers cant be divided by zero")

Enter dividend number : 10
Enter divisor number : 0

Error: numbers cant be divided by zero

#### Given a string count how many vowel it has

In [25]:
vowels = ('a','e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U')

input1 = input("Enter a string input ")
count = 0
for char in input1:
    if(char in vowels):
        count+=1
print(f'Number of vowels present : {count}')

Enter a string input  AEIOUaeiou

Number of vowels present : 10

#### Reverse a list without inbuilt function

In [26]:
input1 = [1,2,3,4,5]
reversed_list = []

for i in range(len(input1) - 1, -1, -1): 
    reversed_list.append(input1[i])

print(reversed_list)

[5, 4, 3, 2, 1]

#### Create a dictionary with atleast 5 key value pairs

In [2]:
import pandas as pd

student_name_age = {'Name' : ["Meenakshi", "Akshaya", "Divya", "Swathy", "Maha"],
                    'age' : [27, 21, 22, 23, 28] }


print(student_name_age)

{'Name': ['Meenakshi', 'Akshaya', 'Divya', 'Swathy', 'Maha'], 'age': [27, 21, 22, 23, 28]}

#### Write a pandas code to readcsv file and print top 5 rows

In [33]:
import pandas as pd

pd.read_csv("employee_data.csv").head(5)

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

#### Create a dataframe from dictionary

In [36]:
student_name_age = {'Name' : ["Meenakshi", "Akshaya", "Divya", "Swathy", "Maha"],
                    'age' : [27, 21, 22, 23, 28] }
Student_details = pd.DataFrame(student_name_age)
print(Student_details)

        Name  age
0  Meenakshi   27
1    Akshaya   21
2      Divya   22
3     Swathy   23
4       Maha   28

#### Replace all the missing values in column with mean

In [7]:
import pandas as pd
Student_marks = pd.read_csv("Book1.csv")
print(f"Students marks in original : {Student_marks}")
Student_marks.fillna(Student_marks.mean(numeric_only=True), inplace= True)
Student_marks

Students marks in original :         ID       Name  Tamil  English  Math  Science  Social
0   413950  Meenakshi   95.0     93.0  98.0     92.0     NaN
1   413951     Ankita   98.0      NaN  93.0     99.0    91.0
2   413952     Ananya   90.0     93.0   NaN     91.0    91.0
3   413953        Dev   94.0     91.0  89.0      NaN    98.0
4   413954     Dheena    NaN     78.0  67.0     81.0    87.0
5   413955    Kiruthi   91.0     91.0  93.0     93.0    90.0
6   413956       Diya   89.0     89.0  87.0     87.0    78.0
7   413957  Dharshini   87.0     98.0   NaN     93.0     NaN
8   413958       Teja   98.0      NaN  90.0     98.0    93.0
9   413959   Chaithra   90.0     93.0   NaN     94.0    87.0
10  413960      Veena   93.0     87.0  90.0      NaN    98.0

        ID       Name  Tamil    English    Math  Science     Social
0   413950  Meenakshi   95.0  93.000000  98.000     92.0  90.333333
1   413951     Ankita   98.0  90.333333  93.000     99.0  91.000000
2   413952     Ananya   90.0  93.000000  88.375     91.0  91.000000
3   413953        Dev   94.0  91.000000  89.000     92.0  98.000000
4   413954     Dheena   92.5  78.000000  67.000     81.0  87.000000
5   413955    Kiruthi   91.0  91.000000  93.000     93.0  90.000000
6   413956       Diya   89.0  89.000000  87.000     87.0  78.000000
7   413957  Dharshini   87.0  98.000000  88.375     93.0  90.333333
8   413958       Teja   98.0  90.333333  90.000     98.0  93.000000
9   413959   Chaithra   90.0  93.000000  88.375     94.0  87.000000
10  413960      Veena   93.0  87.000000  90.000     92.0  98.000000

In [16]:
import pandas as pd

Student_details = pd.read_csv("Book1.csv")

Student_above_30 = Student_details[Student_details['Age']>=30]
Student_above_30

        ID     Name  Tamil  English  Math  Science  Social  Age
4   413954   Dheena    NaN     78.0  67.0     81.0    87.0   30
5   413955  Kiruthi   91.0     91.0  93.0     93.0    90.0   30
6   413956     Diya   89.0     89.0  87.0     87.0    78.0   32
8   413958     Teja   98.0      NaN  90.0     98.0    93.0   34
10  413960    Veena   93.0     87.0  90.0      NaN    98.0   33